### ISSUE TITLE
希望能触点drools的实战文档，更有助新手学习

### ISSUE THREAD

**Issue by lockbur** [WalterInSH/risk-management-note#1]
希望能触点drools的实战文档，更有助新手学习

**Comment by WalterInSH** [comment]
@lockbur 十分感谢你的建议

实事求是的讲，由于我们当时在调研后，决定自研规则引擎，drools guvnor并没有使用太久，也就没有更多使用经验了。

不过你可以参考官方文档，没有比这个更适合的了
http://docs.jboss.org/drools/release/5.6.0.Final/drools-guvnor-docs/html_single/index.html
