### ISSUE TITLE
看完笔记有个疑问

### ISSUE THREAD

**Issue by tuhaolam** [WalterInSH/risk-management-note#2]
防范代理IP中：“3. 购买代理IP。和黑产一样，直接花钱购买代理IP。相比较第二步，我们无需开发爬虫，也可以快速获取大量代理IP”，对抗代理ip与购买代理ip有何关系？但愿你不是说把代理ip买完了不让别人买吧：）

**Comment by WalterInSH** [comment]
代理IP是一个共用资源，不是买一个就少一个。
买了之后，提供商每天可以给你提供1-2万个代理IP，积累一段时间，你就可以积累到大量共用代理IP。

**Comment by tuhaolam** [comment]
如果攻击者购买的代理ip不是公开的，你也没掌握他购买的渠道，那你花钱买的代理ip其实是没用的。我觉得还是你提的第1种思路更好点，对海外ip进行二次验证。或者调用ip信誉库去判断下一步操作。现在360、threadbook的都有商用的。

**Comment by WalterInSH** [comment]
@tuhaolam 好问题

>如果攻击者购买的代理ip不是公开的，你也没掌握他购买的渠道

对于这一点是肯定会出现的，购买代理IP确实没办法解决。但是逻辑上推不出购买代理IP是没用的。

1. 依然会有大量黑产没有购买私有代理IP（成本考虑），不能因为一部分而否定整体无意义
2. 购买代理IP价格便宜，收效快，投入产出比好，值得作为基础防护的必要步骤

**Comment by tuhaolam** [comment]
那就好，这么说这套方案已经是经过验证了。只不过对于防御的一方而言，要去跟进代理ip的购买，成本不小吧，毕竟代理ip厂家和ip池会越来越多、越来越大。
